import { useEffect, useState } from 'react'

import Board from '../../components/Board'
import FullScreenLoader from '../../components/utils/FullscreenLoader'
import Head from 'next/head'
import type { NextPage } from 'next'
import { requireAuth } from '../../utils/requireAuth'
import { trpc } from '../../utils/trpc'
import { useRouter } from 'next/router'

export const getServerSideProps = requireAuth(async (ctx) => {
  return { props: {} }
})

const MyBoard: NextPage = () => {
  const [isBrowser, setIsBrowser] = useState(false)
  const [currentBoard, setCurrentBoard] = useState(0)

  useEffect(() => {
    setIsBrowser(process.browser)
  }, [])

  const router = useRouter()
  const title = router.query.board as string

  const { data: data1 } = trpc.useQuery(['users.me'])

  const { data, error, isLoading, isFetching } = trpc.useQuery([
    'users.board',
    title,
  ])

  // if (!data?.result) return null

  if (isLoading) return <FullScreenLoader />
  if (isFetching) return <FullScreenLoader />

  if (error) return <>{error.message}</>

  console.log(data)
  console.log(data1)

  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>{title}</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {isBrowser ? (
          <Board
            data={data?.selectedBoard?.data}
            title={data?.selectedBoard?.title as string}
          />
        ) : null}
      </main>

      <footer></footer>
    </div>
  )
}
export default MyBoard
