import { ReactElement, useEffect, useState } from 'react'

import Board from '../../components/Board/Board'
import { BoardLayout } from '../../components/Layout/BoardLayout'
import { BoardTitle } from '../../components/Board/BoardTitle'
import FullScreenLoader from '../../components/utils/FullscreenLoader'
import Head from 'next/head'
import { Layout } from '../../components/Layout/Layout'
import type { NextPageWithLayout } from '../_app'
import { requireAuth } from '../../utils/requireAuth'
import { trpc } from '../../utils/trpc'
import { useRouter } from 'next/router'

export const getServerSideProps = requireAuth(async (ctx) => {
  return { props: {} }
})

const MyBoard: NextPageWithLayout = () => {
  const [isBrowser, setIsBrowser] = useState(false)

  useEffect(() => {
    setIsBrowser(process.browser)
  }, [])

  const router = useRouter()
  const title = router.query.board as string

  const { data, error, isLoading, isFetching } = trpc.useQuery([
    'board.board',
    title,
  ])

  // if (isLoading || isFetching) return <BoardSkeleton />
  if (isLoading || isFetching) return <FullScreenLoader />
  // if (isFetching) return

  if (error) return <>{error.message}</>

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='absolute top-2 left-1/2 transform -translate-x-1/2 '>
        <BoardTitle currentTitle={title} textSize='text-3xl' />
      </div>

      {isBrowser && (
        <Board
          data={data?.selectedBoard?.data}
          title={data?.selectedBoard?.title as string}
        />
      )}
    </>
  )
}

MyBoard.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      <BoardLayout>{page}</BoardLayout>
    </Layout>
  )
}

export default MyBoard
