import { useEffect, useState } from 'react'

import Board from '../components/Board'
import FullScreenLoader from '../components/utils/FullscreenLoader'
import Head from 'next/head'
import { Layout } from '../components/Layout'
import type { NextPage } from 'next'
import { requireAuth } from '../utils/requireAuth'
import { trpc } from '../utils/trpc'

export const getServerSideProps = requireAuth(async (ctx) => {
  return { props: {} }
})

const Home: NextPage = () => {
  const [isBrowser, setIsBrowser] = useState(false)
  const [currentBoard, setCurrentBoard] = useState(0)

  useEffect(() => {
    setIsBrowser(process.browser)
  }, [])

  const { data, error, isLoading, isFetching } = trpc.useQuery(['users.me'])

  if (!data?.result) return null

  // if (isLoading) return <FullScreenLoader />
  // if (isFetching) return <FullScreenLoader />

  if (error) return <>{error.message}</>

  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Layout title={data.result.boards[currentBoard].title}>
          {isBrowser ? (
            <Board
              data={data.result.boards[currentBoard].data}
              title={data.result.boards[currentBoard].title}
            />
          ) : null}
        </Layout>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
