import { useEffect, useState } from 'react'

import Board from '../components/Board'
import Head from 'next/head'
import type { NextPage } from 'next'
import { requireAuth } from '../utils/requireAuth'
import { signOut } from 'next-auth/react'
import { trpc } from '../utils/trpc'

export const getServerSideProps = requireAuth(async (ctx) => {
  return { props: {} }
})

const Home: NextPage = () => {
  const [isBrowser, setIsBrowser] = useState(false)

  useEffect(() => {
    setIsBrowser(process.browser)
  }, [])

  const { data, error, isLoading } = trpc.useQuery(['users.me'])

  if (!data?.result) return null

  if (error) return <>{error.message}</>

  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto'>
        <h1>{data.result.title}</h1>
        {isBrowser ? <Board data={data.result.data} /> : null}
      </main>

      <footer className=''>
        <button className='' onClick={() => signOut({ callbackUrl: '/' })}>
          Logout
        </button>
      </footer>
    </div>
  )
}

export default Home
