import Head from 'next/head'
import Link from 'next/link'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <div className='h-screen w-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-evenly h-screen w-full '>
        <Link href='/sign-up' className='link'>
          Sign up
        </Link>
        <Link href='/sign-in' className='link'>
          Sign in
        </Link>
      </main>

      <footer className=''></footer>
    </div>
  )
}

export default Home
