import Head from 'next/head'
import { Layout } from '../components/Layout/Layout'
import Link from 'next/link'
import type { NextPage } from 'next'
import { NextPageWithLayout } from './_app'
import { ReactElement } from 'react'
import { useSession } from 'next-auth/react'

const Home: NextPageWithLayout = () => {
  const { data: session, status } = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='viewport' content='width=device-width, initial-scale=2' />
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex-col items-center my-auto text-center '>
        <h1>hello this is main</h1>
        {session && (
          <Link href='/dashboard'>
            <button className='inline-block mt-2 px-6 py-2 bg-white dark:bg-night-sky font-medium text-md leading-tight rounded-md shadow-md border-2 hover:border-blue-500 transition duration-150 ease-in-out'>
              go to dashboard
            </button>
          </Link>
        )}
      </div>

      <footer className=''>{JSON.stringify(session)}</footer>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export default Home
