import { createUserSchema, SignIn } from '../schema/user.schema'

import Head from 'next/head'
import Link from 'next/link'
import type { NextPage } from 'next'
import { signIn } from 'next-auth/react'
import { useCallback } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeftIcon } from '@radix-ui/react-icons'

const SignIn: NextPage = () => {
  const { register, handleSubmit } = useForm<SignIn>({
    resolver: zodResolver(createUserSchema),
  })

  const onSubmit = useCallback(async (data: SignIn) => {
    await signIn('credentials', { ...data, callbackUrl: '/dashboard' })
  }, [])

  return (
    <div>
      <Head>
        <title>Next App - Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col items-center justify-center h-screen w-full'>
        <form
          className='flex items-center justify-center'
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className=' w-96 bg-base-100 shadow-xl border-2 rounded-md p-4'>
            <div>
              <h1 className='text-xl'>Welcome back!</h1>
              <input
                autoComplete='off'
                type='text'
                placeholder='Type your username...'
                className='h-8 rounded-md pl-2 w-full max-w-xs my-2 dark:bg-black-velvet '
                {...register('username')}
              />
              <input
                autoComplete='off'
                type='password'
                placeholder='Type your password...'
                className='h-8 rounded-md pl-2 w-full max-w-xs my-2 dark:bg-black-velvet '
                {...register('password')}
              />
              <div className='flex justify-between'>
                <button
                  type='submit'
                  className='inline-block mt-2 px-6 py-2 bg-white dark:bg-night-sky font-medium text-md leading-tight rounded-md shadow-md border-2 hover:border-blue-500 transition duration-150 ease-in-out'
                >
                  Login
                </button>
              </div>
            </div>
          </div>
        </form>
        <Link href='/sign-up'>
          <button className='flex items-center m-2 px-4 py-2 bg-white dark:bg-night-sky font-medium text-md leading-tight rounded-md shadow-md border-2 hover:border-blue-500 transition duration-150 ease-in-out'>
            <ArrowLeftIcon className='mr-2' />
            Go to Sign Up
          </button>
        </Link>
      </main>
    </div>
  )
}

export default SignIn
