import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useCallback } from 'react'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'

import { signUpSchema, SignUp } from '../schema/user.schema'
import { trpc } from '../utils/trpc'

const SignUp: NextPage = () => {
  const router = useRouter()
  const { register, handleSubmit } = useForm<SignUp>({
    resolver: zodResolver(signUpSchema),
  })

  const { mutate, error } = trpc.useMutation(['users.signup'], {
    onSuccess: () => {
      router.push('/sign-in')
    },
  })

  const onSubmit = useCallback(
    (values: SignUp) => {
      mutate(values)
    },
    [mutate]
  )

  return (
    <div>
      <Head>
        <title>Next App - Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <form
          className='flex items-center justify-center h-screen w-full'
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className=' w-96 bg-base-100 shadow-xl'>
            <div className=''>
              <h1 className='text-xl'>Create an account!</h1>
              <h2 className='text-rose-500'>{error && error.message}</h2>
              <input
                type='text'
                placeholder='Type your username...'
                className='input input-bordered w-full max-w-xs my-2 bg-black-velvet'
                {...register('username')}
              />
              <input
                type='email'
                placeholder='Type your email...'
                className='input input-bordered w-full max-w-xs bg-black-velvet'
                {...register('email')}
              />
              <input
                type='password'
                placeholder='Type your password...'
                className='input input-bordered w-full max-w-xs my-2 bg-black-velvet'
                {...register('password')}
              />
              <div className='flex justify-between'>
                <Link href='/sign-in' className='link'>
                  Go to login
                </Link>
                <button className='' type='submit'>
                  Sign Up
                </button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  )
}

export default SignUp
